var trainings = {
  "response": [
    {
      "id": 1,
      "name": "Web Development",
      "date": "Jan 02 -05, 2025",
      "time": "08:30 am - 12:30 pm",
      "oldPrice": "\$715",
      "newPrice": "\$405",
      "country": {"country": "Algeria", "abbreviation": "DZ"},
      "trainer": {
        "id": 000111,
        "first_name": "Maria",
        "last_name": "Carpenter",
        "email": "mcarpentera@so-net.ne.jp",
        "imageUrl": "2015-05-16",
      },
      "imageUrl": "https://getblogo.com/wp-content/uploads/2020/06/1-8.jpg",
    },
    {
      "id": 2,
      "name": "Mobile App Development",
      "date": "Dec 13 -14, 2024",
      "time": "06:30 pm - 08:00 pm",
      "oldPrice": "\$495",
      "newPrice": "\$400",
      "country": {"country": "Cyprus", "abbreviation": "CY"},
      "trainer": {
        "id": 000118,
        "first_name": "Sara",
        "last_name": "Harris",
        "email": "sharris7@deliciousdays.com",
        "imageUrl": "2015-05-16",
      },
      "imageUrl":
          "https://tse3.mm.bing.net/th?id=OIP.OQ5c4fioszziKP5oKTCF9QHaCm&pid=Api&P=0&h=180",
    },
    {
      "id": 3,
      "name": "Cybersecurity Courses",
      "date": "Sep 08 -13, 2024",
      "time": "03:00 pm - 05:30 pm",
      "oldPrice": "\$111",
      "newPrice": "\$99",
      "country": {"country": "India", "abbreviation": "IN"},
      "trainer": {
        "id": 000115,
        "first_name": "Laura",
        "last_name": "Harper",
        "email": "lharper4@boston.com",
        "imageUrl": "2015-05-16",
      },
      "imageUrl":
          "https://tse1.mm.bing.net/th?id=OIP.3EbFGW-Tb-VkOsIfRgOCcgHaE3&pid=Api&P=0&h=180",
    },
    {
      "id": 4,
      "name": "Cloud Computing",
      "date": "Jun 26 -27, 2025",
      "time": "11:30 am - 01:30 pm",
      "oldPrice": "\$310",
      "newPrice": "\$299",
      "country": {"country": "Liechtenstein", "abbreviation": "LI"},
      "trainer": {
        "id": 000112,
        "first_name": "Albert",
        "last_name": "Williamson",
        "email": "awilliamson1@narod.ru",
        "imageUrl": "2015-05-16",
      },
      "imageUrl":
          "http://www.markalexandergolfphotography.com/wp-content/uploads/2019/10/Dumbarnie.15.08.19.MKIV_.7.cor_.jpg",
    },
    {
      "id": 5,
      "name": "Digital Marketing",
      "date": "Nov 01 -03, 2024",
      "time": "08:00 pm - 09:30 pm",
      "oldPrice": "\$564",
      "newPrice": "\$465",
      "country": {"country": "Yemen", "abbreviation": "YE"},
      "trainer": {
        "id": 000115,
        "first_name": "Marie",
        "last_name": "George",
        "email": "mgeorgee@squarespace.com",
        "imageUrl": "2015-05-16",
      },
      "imageUrl":
          "https://www.frci.org.uk/images/custom/uploads/208/images/computer-course-banners-top.jpg",
    },
    {
      "id": 6,
      "name": "Hardware & Networking",
      "date": "Mar 20 -22, 2025",
      "time": "09:30 am - 10:30 am",
      "oldPrice": "\$843",
      "newPrice": "\$763",
      "country": {"country": "Zambia", "abbreviation": "ZM"},
      "trainer": {
        "id": 000113,
        "first_name": "Phillip",
        "last_name": "Mitchell",
        "email": "pmitchellc@ebay.co.uk",
        "imageUrl": "2015-05-16",
      },
      "imageUrl":
          "https://images.inc.com/uploaded_files/image/1920x1080/getty_933383882_2000133420009280345_410292.jpg",
    },
    {
      "id": 7,
      "name": "Software Development",
      "date": "Oct 17 -18, 2024",
      "time": "07:30 am - 09:30 am",
      "oldPrice": "\$436",
      "newPrice": "\$329",
      "country": {"country": "Guernsey", "abbreviation": "GG"},
      "trainer": {
        "id": 000110,
        "first_name": "Roger",
        "last_name": "Alvarez",
        "email": "ralvarez9@nsw.gov.au",
        "imageUrl": "2015-05-16",
      },
      "imageUrl":
          "https://ectatraining.co.uk/wp-content/uploads/2018/08/background-courses.jpg",
    },
    {
      "id": 8,
      "name": "VFX and Animation",
      "date": "Mar 23 -27, 2024",
      "time": "02:30 pm - 04:00 pm",
      "oldPrice": "\$695",
      "newPrice": "\$666",
      "country": {"country": "Denmark", "abbreviation": "DK"},
      "trainer": {
        "id": 000117,
        "first_name": "Michael",
        "last_name": "Rice",
        "email": "mrice6@geocities.jp",
        "imageUrl": "2015-05-16",
      },
      "imageUrl":
          "https://instructor-academy.onlinecoursehost.com/content/images/size/w1000/2023/05/How-to-Create-an-Online-Course-For-Free--Complete-Guide--6.jpg",
    },
    {
      "id": 9,
      "name": "Data Science",
      "date": "May 05 -08, 2024",
      "time": "08:30 pm - 10:30 pm",
      "oldPrice": "\$700",
      "newPrice": "\$632",
      "country": {"country": "Afghanistan", "abbreviation": "AF"},
      "trainer": {
        "id": 000114,
        "first_name": "Russell",
        "last_name": "Robinson",
        "email": "rrobinson3@google.pl",
        "imageUrl": "2015-05-16",
      },
      "imageUrl": "https://wallpaperaccess.com/full/4107359.jpg",
    },
    {
      "id": 10,
      "name": "Machine Learning",
      "date": "Oct 15 -18, 2024",
      "time": "09:00 am - 11:30 am",
      "oldPrice": "\$199",
      "newPrice": "\$99",
      "country": {"country": "Cuba", "abbreviation": "CU"},
      "trainer": {
        "id": 000111,
        "first_name": "Gary",
        "last_name": "Ortiz",
        "email": "gortiz0@mapy.cz",
        "imageUrl": "2015-05-16",
      },
      "imageUrl":
          "https://instructor-academy.onlinecoursehost.com/content/images/size/w2000/2023/05/26_What-To-Do-If-Nobody-Is-Buying-Your-Online-Courses--12-Proven-Strategies-.jpg",
    },
  ]
};
